#!/usr/bin/env python3
"""
Patch Hermes to expose an ``stt_status`` agent tool that returns ground-truth
STT configuration and runtime state.

Why this patch exists
─────────────────────
When the user asks "which STT model are you using?" the agent previously had
no way to answer with certainty — it could only guess from its system prompt.
This patch adds an ``stt_status`` tool that reads:

  - ``stt.enabled``, ``stt.provider``, ``stt.local.model`` from
    ``~/.hermes/config.yaml`` (configured values)
  - ``_local_model_name`` from ``tools.transcription_tools`` (the model
    actually loaded in memory, set by ``_transcribe_local`` or the warmup
    thread)
  - ``_STT_READY`` from ``tui_gateway.server`` (set by
    ``patch-hermes-stt-warmup.py`` when warmup completes)

Two sub-patches are applied:

  Patch A — new file ``tools/stt_introspect_tool.py``
      Created at the target path. Contains the tool logic and the top-level
      ``registry.register()`` call that ``model_tools.discover_builtin_tools``
      picks up automatically via AST scan — no manual import needed.

  Patch B — ``toolsets.py`` entry
      Inserts an ``"stt_introspect"`` entry into ``TOOLSETS`` immediately
      after the ``"cronjob"`` block so the toolset is recognised at runtime.

After patching, add ``stt_introspect`` to your platform toolsets (e.g. via
``patch-hermes-config.py`` or by editing ``~/.hermes/config.yaml``) then
restart Hermes so the patched modules reload.

Idempotency
───────────
Re-runnable. Patch A is skipped when the marker
``HERMES_PATCH:stt-introspect-tool`` is already present in the target file.
Patch B uses ``HERMES_PATCH:stt-introspect-toolset:start/end`` markers.

Usage
─────
    python3 scripts/patch-hermes-stt-introspect.py
    python3 scripts/patch-hermes-stt-introspect.py --lib /opt/hermes
    python3 scripts/patch-hermes-stt-introspect.py --check
    python3 scripts/patch-hermes-stt-introspect.py --unpatch

Docker example:
    docker cp scripts/patch-hermes-stt-introspect.py hermes:/tmp/introspect-patch.py
    docker exec hermes /opt/hermes/.venv/bin/python /tmp/introspect-patch.py --lib /opt/hermes

``scripts/post-hermes-update.sh`` calls this script automatically (step 2cd).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

DEFAULT_HERMES_LIB = Path("/usr/local/lib/hermes-agent")

# ─── Patch A: new tool file ───────────────────────────────────────────────────
PA_TARGET = "tools/stt_introspect_tool.py"
PA_MARKER = "HERMES_PATCH:stt-introspect-tool"

# Plain string concatenation — no f-string so literal `{` / `}` in the Python
# source aren't misread as format placeholders (mirrors patch-hermes-stt-warmup.py).
PA_CONTENT = (
    '"""\n'
    + "HERMES_PATCH:stt-introspect-tool — generated by scripts/patch-hermes-stt-introspect.py.\n"
    + "Do not edit; re-run the patch to update.\n"
    + "\n"
    + "Exposes an ``stt_status`` tool the agent can call to get ground-truth STT\n"
    + "state (configured model, loaded model, provider, ready flag).\n"
    + '"""\n'
    + "\n"
    + "from typing import Any, Dict\n"
    + "from pathlib import Path\n"
    + "import yaml\n"
    + "\n"
    + "from hermes_constants import get_hermes_home\n"
    + "from tools.registry import registry\n"
    + "\n"
    + "STT_STATUS_SCHEMA = {\n"
    + '    "type": "object",\n'
    + '    "properties": {},\n'
    + '    "required": [],\n'
    + "}\n"
    + "\n"
    + "\n"
    + "def _get_stt_status() -> Dict[str, Any]:\n"
    + '    """Read STT config from disk and live state from module globals.\n'
    + "\n"
    + "    Returns:\n"
    + "        Dict with keys: enabled, provider, configured_model, loaded_model, ready.\n"
    + '    """\n'
    + "    hermes_home = get_hermes_home()\n"
    + '    cfg_path = Path(hermes_home) / "config.yaml"\n'
    + '    configured: Dict[str, Any] = {"enabled": True, "provider": "local", "local": {"model": "base"}}\n'
    + "    if cfg_path.exists():\n"
    + "        try:\n"
    + '            cfg = yaml.safe_load(cfg_path.read_text(encoding="utf-8")) or {}\n'
    + '            configured = cfg.get("stt", configured) or configured\n'
    + "        except Exception:\n"
    + "            pass\n"
    + "\n"
    + '    enabled = bool(configured.get("enabled", True))\n'
    + '    provider = configured.get("provider", "local")\n'
    + "    configured_model: str | None\n"
    + '    if provider == "local":\n'
    + '        configured_model = configured.get("local", {}).get("model", "base")\n'
    + "    else:\n"
    + "        configured_model = None\n"
    + "\n"
    + "    # Live state from transcription_tools module globals (set by warmup or first call)\n"
    + "    loaded_model: str | None = None\n"
    + "    try:\n"
    + "        from tools import transcription_tools as _tt\n"
    + '        loaded_model = getattr(_tt, "_local_model_name", None)\n'
    + "    except Exception:\n"
    + "        pass\n"
    + "\n"
    + "    # Warmup readiness from tui_gateway.server (set by patch-hermes-stt-warmup)\n"
    + "    ready = False\n"
    + "    try:\n"
    + "        from tui_gateway import server as _srv\n"
    + '        ev = getattr(_srv, "_STT_READY", None)\n'
    + "        if ev is not None and hasattr(ev, \"is_set\"):\n"
    + "            ready = bool(ev.is_set())\n"
    + "        elif loaded_model is not None:\n"
    + "            # Warmup patch not installed — fall back to model presence.\n"
    + "            ready = True\n"
    + "    except Exception:\n"
    + "        ready = loaded_model is not None\n"
    + "\n"
    + "    return {\n"
    + '        "enabled": enabled,\n'
    + '        "provider": provider,\n'
    + '        "configured_model": configured_model,\n'
    + '        "loaded_model": loaded_model,\n'
    + '        "ready": ready,\n'
    + "    }\n"
    + "\n"
    + "\n"
    + "def stt_status_tool(args: Dict[str, Any], **_kw: Any) -> Dict[str, Any]:\n"
    + '    """Return ground-truth STT configuration and runtime readiness.\n'
    + "\n"
    + "    Args:\n"
    + "        args: Tool arguments (none required).\n"
    + "\n"
    + "    Returns:\n"
    + "        Dict with keys:\n"
    + "          enabled:          Whether STT is enabled in config.\n"
    + "          provider:         Configured provider (e.g. 'local', 'openai').\n"
    + "          configured_model: Model name from config (local provider only).\n"
    + "          loaded_model:     Model currently loaded in memory (None if not yet loaded).\n"
    + "          ready:            True if the model is loaded and ready for transcription.\n"
    + '    """\n'
    + "    return _get_stt_status()\n"
    + "\n"
    + "\n"
    + "registry.register(\n"
    + '    name="stt_status",\n'
    + '    toolset="stt_introspect",\n'
    + "    schema=STT_STATUS_SCHEMA,\n"
    + "    handler=lambda args, **kw: stt_status_tool(args, **kw),\n"
    + '    emoji="\U0001f3a4",\n'
    + ")\n"
)

# ─── Patch B: toolsets.py entry ───────────────────────────────────────────────
# Anchor: the closing `},` of the "cronjob" toolset block, followed by a blank
# line and the "messaging" entry. We insert the new block AFTER the anchor.
PB_TARGET = "toolsets.py"
PB_ANCHOR = (
    '    "cronjob": {\n'
    + '        "description": "Cronjob management tool - create, list, update, pause, resume, remove, and trigger scheduled tasks",\n'
    + '        "tools": ["cronjob"],\n'
    + '        "includes": []\n'
    + "    },"
)
PB_MARK_START = "    # HERMES_PATCH:stt-introspect-toolset:start"
PB_MARK_END = "    # HERMES_PATCH:stt-introspect-toolset:end"
PB_BLOCK = (
    "\n"
    + PB_MARK_START + "\n"
    + '    "stt_introspect": {\n'
    + '        "description": "Inspect live STT (speech-to-text) configuration and runtime state",\n'
    + '        "tools": ["stt_status"],\n'
    + '        "includes": []\n'
    + "    },\n"
    + PB_MARK_END
)

PATCHES = [
    {
        "name": "stt-introspect-toolset",
        "target": PB_TARGET,
        "anchor": PB_ANCHOR,
        "mark_start": PB_MARK_START,
        "mark_end": PB_MARK_END,
        "block": PB_BLOCK,
        "mode": "patch",
    },
]

# ─── implementation ───────────────────────────────────────────────────────────


def is_patched(src: str, p: dict) -> bool:
    return p["mark_start"] in src and p["mark_end"] in src


def apply_patch(src: str, p: dict) -> str | None:
    """Insert block immediately after anchor line."""
    if p["anchor"] not in src:
        return None
    return src.replace(p["anchor"], p["anchor"] + "\n" + p["block"], 1)


def remove_patch(src: str, p: dict) -> str:
    if not is_patched(src, p):
        return src
    start = src.index(p["mark_start"])
    end = src.index(p["mark_end"]) + len(p["mark_end"])
    # Trim the leading newline injected during apply so removal is exact.
    if start > 0 and src[start - 1] == "\n":
        start -= 1
    return src[:start] + src[end:]


def apply_create(target: Path, content: str, marker: str) -> bool:
    """Create a new file with the patch content. Idempotent — no-ops if marker already present.

    Args:
        target:  Destination path.
        content: Full file content to write.
        marker:  Idempotency marker string expected in the file when already patched.

    Returns:
        True if the file was written, False if already present.
    """
    if target.exists():
        existing = target.read_text(encoding="utf-8")
        if marker in existing:
            return False  # already created by a previous run
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return True


def remove_create(target: Path, marker: str) -> bool:
    """Remove a file created by apply_create. No-ops if marker is absent.

    Args:
        target: File to remove.
        marker: Idempotency marker — only deletes if present.

    Returns:
        True if the file was removed, False if not present or marker missing.
    """
    if not target.exists():
        return False
    existing = target.read_text(encoding="utf-8")
    if marker not in existing:
        return False
    target.unlink()
    return True


def resolve_target(lib_root: Path, rel: str, override: Path | None) -> Path:
    if override is not None:
        return override
    return lib_root / rel


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--lib",
        type=Path,
        default=DEFAULT_HERMES_LIB,
        help="Hermes installation root (default: /usr/local/lib/hermes-agent)",
    )
    ap.add_argument(
        "--target",
        type=Path,
        help="override path for a single-target run (skips path resolution from --lib)",
    )
    ap.add_argument("--check", action="store_true", help="exit 0 if all patches present, 1 otherwise")
    ap.add_argument("--unpatch", action="store_true", help="remove all patch blocks")
    ns = ap.parse_args()

    failed = 0

    # ── Patch A: file-create ──────────────────────────────────────────────────
    pa_target = resolve_target(ns.lib, PA_TARGET, ns.target)
    pa_name = "stt-introspect-tool"

    if ns.check:
        if pa_target.exists() and PA_MARKER in pa_target.read_text(encoding="utf-8"):
            print(f"[{pa_name}] PATCHED   ({pa_target})")
        else:
            print(f"[{pa_name}] NOT PATCHED ({pa_target})")
            failed = 1
    elif ns.unpatch:
        if remove_create(pa_target, PA_MARKER):
            print(f"[{pa_name}] removed ({pa_target})")
        else:
            print(f"[{pa_name}] not found or marker absent, nothing to remove ({pa_target})")
    else:
        written = apply_create(pa_target, PA_CONTENT, PA_MARKER)
        if written:
            print(f"[{pa_name}] applied  ({pa_target})")
        else:
            print(f"[{pa_name}] already patched ({pa_target}), skipping")

    # ── Patch B: in-place patches ─────────────────────────────────────────────
    for p in PATCHES:
        target = resolve_target(ns.lib, p["target"], ns.target)
        if not target.exists():
            print(f"[{p['name']}] target not found: {target}", file=sys.stderr)
            failed = 1
            continue
        src = target.read_text(encoding="utf-8")

        if ns.check:
            if is_patched(src, p):
                print(f"[{p['name']}] PATCHED   ({target})")
            else:
                print(f"[{p['name']}] NOT PATCHED ({target})")
                failed = 1
            continue

        if ns.unpatch:
            new_src = remove_patch(src, p)
            if new_src == src:
                print(f"[{p['name']}] not patched, nothing to remove ({target})")
                continue
            target.write_text(new_src, encoding="utf-8")
            print(f"[{p['name']}] removed ({target})")
            continue

        if is_patched(src, p):
            print(f"[{p['name']}] already patched ({target}), skipping")
            continue

        new_src = apply_patch(src, p)
        if new_src is None:
            print(
                f"[{p['name']}] anchor not found in {target}; "
                "patch needs an update for the current Hermes version",
                file=sys.stderr,
            )
            failed = 1
            continue

        target.write_text(new_src, encoding="utf-8")
        print(f"[{p['name']}] applied  ({target})")

    return failed


if __name__ == "__main__":
    sys.exit(main())
